# Generated by Django 5.2.5 on 2025-09-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_contacts_options_favorite_favoriteitem'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='favoriteitem',
        #     name='favorite',
        # ),
        migrations.AlterUniqueTogether(
            name='favoriteitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favoriteitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='FavoriteItem',
        ),
    ]
