# Generated by Django 5.2.5 on 2025-09-29 03:54

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_favoriteitem_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='house_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
