# Generated by Django 5.2.5 on 2025-08-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default='', upload_to='product_category_images/'),
        ),
    ]
