# Generated by Django 5.2.5 on 2025-08-31 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_productcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='types',
        ),
    ]
