# Generated by Django 5.2.5 on 2025-08-14 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('working_hours_start', models.TimeField(verbose_name='Начало работы')),
                ('working_hours_end', models.TimeField(verbose_name='Конец работы')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона (1)')),
                ('phone_number2', models.CharField(max_length=255, verbose_name='Номер телефона (2)')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='social_logos/')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.CharField(max_length=1000, verbose_name='Ссылка')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.sitesettings', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Социальные сети',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
