# Generated by Django 5.2.5 on 2025-08-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_product_type'),
        ('theme', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Главная страница', max_length=255, verbose_name='Название подборки')),
                ('products', models.ManyToManyField(limit_choices_to=8, to='catalog.product', verbose_name='Товары для главной')),
            ],
            options={
                'verbose_name': 'Товары на главной',
                'verbose_name_plural': 'Товары на главной',
            },
        ),
    ]
