# Generated by Django 5.2.5 on 2025-08-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_product_type'),
        ('theme', '0003_featuredproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproducts',
            name='products',
            field=models.ManyToManyField(to='catalog.product', verbose_name='Товары для главной'),
        ),
    ]
