# Generated by Django 5.2.5 on 2025-09-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_alter_featuredproducts_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bg_transparent_logo',
            field=models.ImageField(default='...', upload_to='logos/'),
        ),
    ]
